# wrangler.toml
name = "buch-course"
compatibility_date = "2024-12-15"

<<<<<<< HEAD
# Это отключает кастомные команды и заставляет Pages использовать стандартный процесс
[build]
command = ""
=======
# Указываем, что это Pages-проект с функциями
pages_build_output_dir = "."

# Важно: включаем поддержку функций в папке /functions
[functions]
# ничего не нужно писать — Cloudflare автоматически найдёт /functions/api/
>>>>>>> bade8d796cca1c7af1ec7610c6010ec0c488537c
